version: '3'
services:
    lazyrecon:
        build: .
        container_name: lazyrecon_docker
        image: lazyrecon_docker:latest
        volumes:
         - ./lazyrecon_results/:/home/lazyrecon_user/tools/lazyrecon/lazyrecon_results/